name: Test TikTok Download & Process

on:
  workflow_dispatch: # تشغيل يدوي بضغطة زر

jobs:
  test_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install yt-dlp & FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Run Test Script
      run: node index.js

    - name: Upload Processed Video
      uses: actions/upload-artifact@v4
      with:
        name: my-processed-video
        path: processed_video.mp4
